// chatgpt-generated mock data

const mockData = [
  'banana',
  'apple',
  'orange',
  'grape',
  'watermelon',
  'kiwi',
  'pineapple',
  'strawberry',
  'blueberry',
  'cherry',
  'peach',
  'plum',
  'pear',
  'apricot',
  'lemon',
  'lime',
  'coconut',
  'avocado',
  'pomegranate',
  'mango',
  'fig',
  'grapefruit',
  'raspberry',
  'blackberry',
  'cantaloupe',
  'honeydew',
  'nectarine',
  'dragonfruit',
  'guava',
  'lychee',
  'persimmon',
  'tangerine',
  'kumquat',
  'passionfruit',
  'cucumber',
  'carrot',
  'potato',
  'tomato',
  'broccoli',
  'cauliflower',
  'asparagus',
  'spinach',
  'kale',
  'lettuce',
  'cabbage',
  'bell pepper',
  'onion',
  'garlic',
  'ginger',
  'celery',
  'parsley',
  'cilantro',
  'basil',
  'thyme',
  'oregano',
  'rosemary',
  'mint',
  'dill',
  'bay leaf',
  'chives',
  'sage',
  'turmeric',
  'cinnamon',
  'nutmeg',
  'cloves',
  'vanilla',
  'cumin',
  'coriander',
  'paprika',
  'cayenne',
  'mustard',
  'chili powder',
  'garlic powder',
  'onion powder',
  'black pepper',
  'salt',
  'sugar',
  'honey',
  'maple syrup',
  'molasses',
  'olive oil',
  'vegetable oil',
  'coconut oil',
  'butter',
  'margarine',
  'cream',
  'milk',
  'cheese',
  'yogurt',
  'sour cream',
  'cream cheese',
  'ice cream',
  'whipped cream',
  'egg',
  'bacon',
  'sausage',
  'ham',
  'steak',
  'chicken',
  'turkey',
  'duck',
  'lamb',
  'pork',
  'beef',
  'fish',
  'shrimp',
  'lobster',
  'crab',
  'scallop',
  'clam',
  'oyster',
  'squid',
  'octopus',
  'mussels',
  'anchovy',
  'tuna',
  'salmon',
  'trout',
  'haddock',
  'cod',
  'tilapia',
  'catfish',
  'swordfish',
  'snapper',
  'halibut',
  'sardine',
  'mackerel',
  'herring',
  'whitefish',
  'bass',
  'perch',
  'carp',
  'pickerel',
  'walleye',
  'bluegill',
  'crappie',
  'sunfish',
  'pumpkin',
  'squash',
  'zucchini',
  'cucumber',
  'eggplant',
  'bell pepper',
  'tomato',
  'corn',
  'beans',
  'peas',
  'potato',
  'sweet potato',
  'yam',
  'onion',
  'garlic',
  'carrot',
  'celery',
  'lettuce',
  'spinach',
  'kale',
  'collard greens',
  'swiss chard',
  'beet',
  'turnip',
  'radish',
  'parsnip',
  'rutabaga',
  'brussels sprouts',
  'cabbage',
  'cauliflower',
  'broccoli',
  'asparagus',
  'artichoke',
  'okra',
  'green bean',
  'snap pea',
  'snow pea',
  'bell pepper',
  'jalapeno',
  'poblano',
  'habanero',
  'cayenne',
  'banana pepper',
  'cherry pepper',
  'anaheim pepper',
  'chipotle pepper',
  'bell pepper',
  'paprika',
  'serrano pepper',
  'ghost pepper',
  'scotch bonnet pepper',
  'tabasco pepper',
  'sriracha pepper',
  "bird's eye chili pepper",
  'chocolate',
  'vanilla',
  'strawberry',
  'raspberry',
  'blueberry',
  'blackberry',
  'cherry',
  'orange',
  'lemon',
  'lime',
  'grapefruit',
  'pineapple',
  'watermelon',
  'cantaloupe',
  'honeydew',
  'kiwi',
  'apricot',
  'peach',
  'plum',
  'pear',
  'nectarine',
  'coconut',
  'pomegranate',
  'mango',
  'papaya',
  'fig',
  'guava',
  'lychee',
  'dragonfruit',
  'passionfruit',
  'date',
  'blackcurrant',
  'elderberry',
  'gooseberry',
  'kiwifruit',
  'quince',
  'persimmon',
  'starfruit',
  'pumpkin',
  'squash',
  'zucchini',
  'cucumber',
  'eggplant',
  'tomato',
  'corn',
  'pepper',
  'beans',
  'peas',
  'potato',
  'sweet potato',
  'yam',
  'onion',
  'garlic',
  'carrot',
  'celery',
  'lettuce',
  'spinach',
  'kale',
  'collard greens',
  'swiss chard',
  'beet',
  'turnip',
  'radish',
  'parsnip',
  'rutabaga',
  'brussels sprouts',
  'cabbage',
  'cauliflower',
  'broccoli',
  'asparagus',
  'artichoke',
  'okra',
  'green bean',
  'snap pea',
  'snow pea',
  'bell pepper',
  'jalapeno',
  'poblano',
  'habanero',
  'cayenne',
  'banana pepper',
  'cherry pepper',
  'anaheim pepper',
  'chipotle pepper',
  'bell pepper',
  'paprika',
  'serrano pepper',
  'ghost pepper',
  'scotch bonnet pepper',
  'tabasco pepper',
  'sriracha pepper',
  "bird's eye chili pepper",
  'chocolate',

  'vanilla',
  'strawberry',
  'raspberry',
  'blueberry',
  'blackberry',
  'cherry',
  'orange',
  'lemon',
  'lime',
  'grapefruit',
  'pineapple',
  'watermelon',
  'cantaloupe',
  'honeydew',
  'kiwi',
  'apricot',
  'peach',
  'plum',
  'pear',
  'nectarine',
  'coconut',
  'pomegranate',
  'mango',
  'papaya',
  'fig',
  'guava',
  'lychee',
  'dragonfruit',
  'passionfruit',
  'date',
  'blackcurrant',
  'elderberry',
  'gooseberry',
  'kiwifruit',
  'quince',
  'persimmon',
  'starfruit',
  'raspberry jam',
  'strawberry jam',
  'blueberry jam',
  'blackberry jam',
  'cherry jam',
  'orange marmalade',
  'lemon curd',
  'honey',
  'maple syrup',
  'molasses',
  'peanut butter',
  'almond butter',
  'cashew butter',
  'sunflower seed butter',
  'soy butter',
  'coconut butter',
  'chocolate spread',
  'nutella',
  'marshmallow fluff',
  'apple butter',
  'grape jelly',
  'apricot preserves',
  'fig preserves',
  'pumpkin butter',
  'caramel sauce',
  'chocolate sauce',
  'butterscotch sauce',
  'strawberry sauce',
  'raspberry sauce',
  'blueberry sauce',
  'blackberry sauce',
  'cherry sauce',
  'vanilla ice cream',
  'chocolate ice cream',
  'strawberry ice cream',
  'mint chocolate chip ice cream',
  'cookie dough ice cream',
  'cookies and cream ice cream',
  'rocky road ice cream',
  'butter pecan ice cream',
  'coffee ice cream',
  'chocolate chip ice cream',
  'vanilla bean ice cream',
  'chocolate fudge ice cream',
  'pistachio ice cream',
  'neapolitan ice cream',
  'caramel ice cream',
  'moose tracks ice cream',
  'peanut butter ice cream',
  'strawberry cheesecake ice cream',
  'rainbow sherbet ice cream',
  'rum raisin ice cream',
  'black walnut ice cream',
  'maple walnut ice cream',
  'bubblegum ice cream',
  'cotton candy ice cream',
  'red velvet ice cream',
  'cinnamon ice cream',
  'peppermint ice cream',
  'blue moon ice cream',
  'green tea ice cream',
  'lemon sorbet',
  'raspberry sorbet',
  'orange sorbet',
  'lime sorbet',
  'strawberry sorbet',
  'blackberry sorbet',
  'blueberry sorbet',
  'lemonade sorbet',
  'cherry sorbet',
  'pineapple sorbet',
  'coconut sorbet',
  'watermelon sorbet',
  'melon sorbet',
  'papaya sorbet',
  'mango sorbet',
  'passionfruit sorbet',
  'kiwi sorbet',
  'peach sorbet',
  'plum sorbet',
  'pear sorbet',
  'grape sorbet',
  'apple sorbet',
  'banana sorbet',
  'pomegranate sorbet',
  'guava sorbet',
  'lychee sorbet',
  'dragonfruit sorbet',
  'kiwifruit sorbet',
  'quince sorbet',
  'persimmon sorbet',
  'starfruit sorbet',
  'raspberry sherbet',
  'strawberry sherbet',
  'orange sherbet',
  'lime sherbet',
  'lemon sherbet',
  'blueberry sherbet',
  'blackberry sherbet',
  'cherry sherbet',
  'pineapple sherbet',
  'coconut sherbet',
  'watermelon sherbet',
  'melon sherbet',
  'papaya sherbet',
  'mango sherbet',
  'passionfruit sherbet',
  'kiwi sherbet',
  'peach sherbet',
  'plum sherbet',
  'pear sherbet',
  'grape sherbet',
  'apple sherbet',
  'banana sherbet',
  'pomegranate sherbet',
  'guava sherbet',
  'lychee sherbet',
  'dragonfruit sherbet',
  'kiwifruit sherbet',
  'quince sherbet',
  'persimmon sherbet',
  'starfruit sherbet',
  'cantaloupe sherbet',
  'honeydew sherbet',
  'apricot sherbet',
  'fig sherbet',
  'banana split',
  'sundae',
  'ice cream cone',
  'milkshake',
  'root beer float',
  'affogato',
  'gelato',
  'sorbet',
  'sherbet',
  'soft serve',
  'frozen yogurt',
  'popsicle',
  'snow cone',
  'chocolate chip cookie',
  'sugar cookie',
  'oatmeal cookie',
  'peanut butter cookie',
  'gingerbread cookie',
  'snickerdoodle cookie',
  'shortbread cookie',
  'biscotti',
  'macaron',
  'butter cookie',
  'lemon cookie',
  'almond cookie',
  'coconut cookie',
  'chocolate crinkle cookie',
  'thumbprint cookie',
  'pecan sandie',
  'spritz cookie',
  'fortune cookie',
  'm&m cookie',
  'peanut butter blossom',
  'oatmeal raisin cookie',
  'molasses cookie',
  'sugar-free cookie',
  'gluten-free cookie',
  'vegan cookie',
  'double chocolate chip cookie',
  'white chocolate chip cookie',
  'macadamia nut cookie',
  'pistachio cookie',
  'cinnamon roll',
  'croissant',
  'danish',
  'muffin',
  'scone',
  'bagel',
  'toast',
  'english muffin',
  'pancake',
  'waffle',
  'french toast',
  'crepe',
  'donut',
  'bear claw',
  'apple fritter',
  'coffee cake',
  'cinnamon roll',
  'bagel with cream cheese',
  'croissant with butter',
  'danish with fruit',
  'muffin with jam',
  'scone with clotted cream',
  'toast with jam',
  'english muffin with butter',
  'pancake with syrup',
  'waffle with whipped cream',
  'french toast with powdered sugar',
  'crepe with nutella',
  'donut with sprinkles',
  'bear claw with almonds',
  'apple fritter with cinnamon',
  'coffee cake with streusel',
  'bacon and eggs',
  'sausage and toast',
  'ham and cheese omelette',
  'steak and potatoes',
  'chicken and rice',
  'turkey and stuffing',
  'duck and orange sauce',
  'lamb and mint jelly',
  'pork and applesauce',
  'beef and gravy',
  'fish and chips',
  'shrimp and grits',
  'lobster and butter',
  'crab and garlic butter',
  'scallop and bacon',
  'clam and linguine',
  'oyster and mignonette',
  'squid and ink',
  'octopus and olive oil',
  'mussels and wine',
  'anchovy and capers',
  'tuna and mayo',
  'salmon and dill',
  'trout and almonds',
  'haddock and chips',
  'cod and tartar sauce',
  'tilapia and lemon',
  'catfish and hushpuppies',
  'swordfish and salsa',
  'snapper and mango',
  'halibut and spinach',
  'sardine and crackers',
  'mackerel and horseradish',
  'herring and onions',
  'whitefish and lemon',
  'bass and parsley',
  'perch and lemon',
  'carp and vinegar',
  'pickerel and lime',
  'walleye and cilantro',
  'bluegill and jalapeno',
  'crappie and garlic',
  'sunfish and herbs',
  'pumpkin and cinnamon',
  'squash and nutmeg',
  'zucchini and basil',
  'cucumber and dill',
  'eggplant and tomato',
  'bell pepper and onion',
  'tomato and garlic',
  'corn and butter',
  'beans and rice',
  'peas and carrots',
  'potato and cheese',
  'sweet potato and marshmallow',
  'yam and brown sugar',
  'onion and gravy',
  'garlic and olive oil',
  'carrot and ginger',
  'celery and peanut butter',
  'lettuce and ranch',
  'spinach and feta',
  'kale and lemon',
  'collard greens and ham',
  'swiss chard and vinegar',
  'beet and goat cheese',
  'turnip and honey',
  'radish and salt',
  'parsnip and maple syrup',
  'rutabaga and mustard',
  'brussels sprouts and bacon',
  'cabbage and sausage',
  'cauliflower and cheese',
  'broccoli and garlic',
  'asparagus and lemon',
  'artichoke and butter',
  'okra and tomato',
  'green bean and almonds',
  'snap pea and sesame',
  'snow pea and soy sauce',
  'bell pepper and hummus',
  'jalapeno and cream cheese',
  'poblano and cheddar',
  'habanero and lime',
  'cayenne and garlic',
  'banana pepper and vinegar',
  'cherry pepper and cream cheese',
  'anaheim pepper and ranch',
  'chipotle pepper and salsa',
  'bell pepper and guacamole',
  'paprika and sour cream',
  'serrano pepper and cilantro',
  'ghost pepper and yogurt',
  'scotch bonnet pepper and coconut milk',
  'tabasco pepper and lime',
  'sriracha pepper and mayo',
  "bird's eye chili pepper and ginger",
  'chocolate and strawberries',
  'vanilla and cream',
  'strawberry and cream',
  'raspberry and chocolate',
  'blueberry and lemon',
  'blackberry and mint',
  'cherry and almond',
  'orange and chocolate',
  'lemon and poppyseed',
  'lime and coconut',
  'grapefruit and honey',
  'pineapple and rum',
  'watermelon and basil',
  'cantaloupe and prosciutto',
  'honeydew and lime',
  'kiwi and banana',
  'apricot and walnut',
  'peach and bourbon',
  'plum and cinnamon',
  'pear and brie',
  'nectarine and arugula',
  'coconut and lime',
  'pomegranate and goat cheese',
  'mango and chili',
  'papaya and lime',
  'fig and goat cheese',
  'guava and lime',
  'lychee and coconut milk',
  'dragonfruit and kiwi',
  'passionfruit and pineapple',
  'date and walnut',
  'blackcurrant and orange',
  'elderberry and honey',
  'gooseberry and thyme',
  'kiwifruit and strawberry',
  'quince and pear',
  'persimmon and cinnamon',
  'starfruit and lime',
  'pumpkin and spice',
  'squash and soup',
  'zucchini and bread',
  'cucumber and salad',
  'eggplant and parmesan',
  'bell pepper and stuffed',
  'tomato and sauce',
  'corn and chowder',
  'beans and stew',
  'peas and casserole',
  'potato and soup',
  'sweet potato and fries',
  'yam and marshmallow',
  'onion and rings',
  'garlic and bread',
  'carrot and cake',
  'celery and sticks',
  'lettuce and wraps',
  'spinach and dip',
  'kale and chips',
  'collard greens and beans',
  'swiss chard and gratin',
  'beet and salad',
  'turnip and greens',
  'radish and slaw',
  'parsnip and puree',
  'rutabaga and mash',
  'brussels sprouts and bacon',
  'cabbage and rolls',
  'cauliflower and mash',
  'broccoli and salad',
  'asparagus and grill',
  'artichoke and dip',
  'okra and fry',
  'green bean and casserole',
  'snap pea and stir-fry',
  'snow pea and saute',
  'bell pepper and stuffed pepper',
  'jalapeno and popper',
  'poblano and relleno',
  'habanero and salsa',
  'cayenne and sauce',
  'banana pepper and rings',
  'cherry pepper and relish',
  'anaheim pepper and sauce',
  'chipotle pepper and salsa',
  'bell pepper and stuffed pepper',
  'paprika and rub',
  'serrano pepper and sauce',
  'ghost pepper and challenge',
  'scotch bonnet pepper and jerk',
  'tabasco pepper and sauce',
  'sriracha pepper and mayo',
  "bird's eye chili pepper and heat",
  'chocolate and cake',
  'vanilla and frosting',
  'strawberry and shortcake',
  'raspberry and tart',
  'blueberry and pie',

  'blackberry and cobbler',
  'cherry and crumble',
  'orange and marmalade',
  'lemon and bar',
  'lime and pie',
  'grapefruit and sponge',
  'pineapple and upside-down cake',
  'watermelon and sorbet',
  'cantaloupe and smoothie',
  'honeydew and fruit salad',
  'kiwi and pavlova',
  'apricot and clafoutis',
  'peach and crisp',
  'plum and compote',
  'pear and tart',
  'nectarine and galette',
  'coconut and macaroon',
  'pomegranate and parfait',
  'mango and chutney',
  'papaya and bread',
  'fig and pudding',
  'guava and cheesecake',
  'lychee and jelly',
  'dragonfruit and salad',
  'passionfruit and pavlova',
  'date and sticky toffee pudding',
  'blackcurrant and fool',
  'elderberry and syrup',
  'gooseberry and fool',
  'kiwifruit and fool',
  'quince and membrillo',
  'persimmon and bread',
  'starfruit and salad',
  'raspberry and thumbprint cookie',
  'strawberry and jam',
  'blueberry and pancake',
  'blackberry and cobbler',
  'cherry and pie',
  'orange and marmalade',
  'lemon and tart',
  'lime and cheesecake',
  'grapefruit and sorbet',
  'pineapple and upside-down cake',
  'watermelon and smoothie',
  'cantaloupe and salad',
  'honeydew and fruit',
  'kiwi and pavlova',
  'apricot and clafoutis',
  'peach and cobbler',
  'plum and tart',
  'pear and compote',
  'nectarine and galette',
  'coconut and macaroon',
  'pomegranate and parfait',
  'mango and salsa',
  'papaya and salad',
  'fig and bread',
  'guava and juice',
  'lychee and martini',
  'dragonfruit and smoothie',
  'passionfruit and pavlova',
  'date and pudding',
  'blackcurrant and fool',
  'elderberry and syrup',
  'gooseberry and tart',
  'kiwifruit and tart',
  'quince and membrillo',
  'persimmon and bread',
  'starfruit and salad',
  'raspberry and fool',
  'strawberry and parfait',
  'blueberry and crisp',
  'blackberry and crumble',
  'cherry and clafoutis',
  'orange and tart',
  'lemon and curd',
  'lime and pie',
  'grapefruit and brulee',
  'pineapple and sorbet',
  'watermelon and granita',
  'cantaloupe and salad',
  'honeydew and cocktail',
  'kiwi and tart',
  'apricot and pie',
  'peach and cobbler',
  'plum and crumble',
  'pear and tarte tatin',
  'nectarine and crisp',
  'coconut and cake',
  'pomegranate and jelly',
  'mango and smoothie',
  'papaya and bread',
  'fig and jam',
  'guava and pastry',
  'lychee and ice cream',
  'dragonfruit and tart',
  'passionfruit and cheesecake',
  'date and pudding',
  'blackcurrant and cordial',
  'elderberry and wine',
  'gooseberry and jam',
  'kiwifruit and cake',
  'quince and jelly',
  'persimmon and pudding',
  'starfruit and pie',
  'raspberry and tart',
  'strawberry and shortcake',
  'blueberry and muffin',
  'blackberry and pie',
  'cherry and cobbler',
  'orange and marmalade',
  'lemon and pound cake',
  'lime and tart',
  'grapefruit and sorbet',
  'pineapple and cake',
  'watermelon and popsicle',
  'cantaloupe and smoothie',
  'honeydew and salad',
  'kiwi and jam',
  'apricot and jam',
  'peach and pie',
  'plum and crumble',
  'pear and cake',
  'nectarine and tart',
  'coconut and pie',
  'pomegranate and sorbet',
  'mango and salsa',
  'papaya and jam',
  'fig and bread',
  'guava and pastry',
  'lychee and martini',
  'dragonfruit and smoothie',
  'passionfruit and tart',
  'date and pudding',
  'blackcurrant and sauce',
  'elderberry and syrup',
  'gooseberry and pie',
  'kiwifruit and pavlova',
  'quince and tart',
  'persimmon and bread',
  'starfruit and salad',
  'raspberry and sauce',
  'strawberry and jam',
  'blueberry and pie',
  'blackberry and crumble',
  'cherry and compote',
  'orange and marmalade',
  'lemon and curd',
  'lime and tart',
  'grapefruit and sorbet',
  'pineapple and cake',
  'watermelon and smoothie',
  'cantaloupe and salad',
  'honeydew and fruit',
  'kiwi and pie',
  'apricot and cake',
  'peach and cobbler',
  'plum and tart',
  'pear and jam',
  'nectarine and compote',
  'coconut and ice cream',
  'pomegranate and parfait',
  'mango and salsa',
  'papaya and bread',
  'fig and jam',
  'guava and pastry',
  'lychee and martini',
  'dragonfruit and smoothie',
  'passionfruit and tart',
  'date and pudding',
  'blackcurrant and sauce',
  'elderberry and syrup',
  'gooseberry and pie',
  'kiwifruit and pavlova',
  'quince and tart',
  'persimmon and bread',
  'starfruit and salad',
  'chocolate and chip cookie',
  'vanilla and ice cream',
  'strawberry and jam',
  'raspberry and sauce',
  'blueberry and pie',
  'blackberry and crumble',
  'cherry and compote',
  'orange and marmalade',
  'lemon and curd',
  'lime and pie',
  'grapefruit and sorbet',
  'pineapple and cake',
  'watermelon and smoothie',
  'cantaloupe and salad',
  'honeydew and fruit',
  'kiwi',
];

module.exports = mockData;
